
services:
  #  Health Checks
  applications.fungus.controllers.StatusGetController:
    class: ../../controllers/HealthChecks/StatusGetController
    arguments: []

  #  Harvests
  fungus.harvests.InMemoryHarvestRepository:
    class: ../../../../src/Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  fungus.harvests.HarvestCreator:
    class: ../../../../src/Fungus/Harvests/Application/create/HarvestCreator
    arguments: ["@fungus.harvests.InMemoryHarvestRepository", "@fungus.mushrooms.InMemoryMushroomRepository", "@fungus.locations.InMemoryLocationRepository"]

  fungus.harvests.HarvestCleaner:
    class: ../../../../src/Fungus/Harvests/Application/clean/HarvestCleaner
    arguments: ["@fungus.harvests.InMemoryHarvestRepository"]

  fungus.harvests.HarvestsByLocationFinder:
    class: ../../../../src/Fungus/Harvests/Application/FindByLocation/HarvestsByLocationFinder
    arguments: ["@fungus.harvests.InMemoryHarvestRepository"]

  applications.fungus.controllers.HarvestsPutController:
    class: ../../controllers/Harvests/HarvestsPutController
    arguments: ["@fungus.harvests.HarvestCreator"]

  applications.fungus.controllers.HarvestsDeleteController:
    class: ../../controllers/Harvests/HarvestsDeleteController
    arguments: ["@fungus.harvests.HarvestCleaner"]

  applications.fungus.controllers.HarvestsByLocationGetController:
    class: ../../controllers/Harvests/HarvestsByLocationGetController
    arguments: ["@fungus.harvests.HarvestsByLocationFinder"]

  #  Mushrooms
  fungus.mushrooms.InMemoryMushroomRepository:
    class: ../../../../src/Fungus/Mushrooms/Infrastructure/InMemoryMushroomRepository
    arguments: []

  fungus.mushrooms.MushroomCreator:
    class: ../../../../src/Fungus/Mushrooms/Application/create/MushroomCreator
    arguments: ["@fungus.mushrooms.InMemoryMushroomRepository"]

  fungus.mushrooms.MushroomsCleaner:
    class: ../../../../src/Fungus/Mushrooms/Application/clean/MushroomsCleaner
    arguments: ["@fungus.mushrooms.InMemoryMushroomRepository"]

  fungus.mushrooms.MushroomsSearcher:
    class: ../../../../src/Fungus/Mushrooms/Application/SearchAll/MushroomsSearcher
    arguments: ["@fungus.mushrooms.InMemoryMushroomRepository"]

  applications.fungus.controllers.MushroomPutController:
    class: ../../controllers/Mushrooms/MushroomPutController
    arguments: ["@fungus.mushrooms.MushroomCreator"]

  applications.fungus.controllers.MushroomsDeleteController:
    class: ../../controllers/Mushrooms/MushroomsDeleteController
    arguments: ["@fungus.mushrooms.MushroomsCleaner"]

  applications.fungus.controllers.MushroomsGetController:
    class: ../../controllers/Mushrooms/MushroomsGetController
    arguments: ["@fungus.mushrooms.MushroomsSearcher"]

  #  Locations
  fungus.locations.InMemoryLocationRepository:
    class: ../../../../src/Fungus/Locations/Infrastructure/InMemoryLocationRepository
    arguments: []

  fungus.locations.LocationCreator:
    class: ../../../../src/Fungus/Locations/Application/create/LocationCreator
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  fungus.locations.LocationsFinder:
    class: ../../../../src/Fungus/Locations/Application/Find/LocationsFinder
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  fungus.locations.LocationByIdFinder:
    class: ../../../../src/Fungus/Locations/Application/FindById/LocationByIdFinder
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  fungus.locations.LocationCleaner:
    class: ../../../../src/Fungus/Locations/Application/clean/LocationCleaner
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  applications.fungus.controllers.LocationPutController:
    class: ../../controllers/Locations/LocationPutController
    arguments: ["@fungus.locations.LocationCreator"]

  applications.fungus.controllers.LocationsGetController:
    class: ../../controllers/Locations/LocationsGetController
    arguments: ["@fungus.locations.LocationsFinder"]

  applications.fungus.controllers.LocationByIdGetController:
    class: ../../controllers/Locations/LocationByIdGetController
    arguments: ["@fungus.locations.LocationByIdFinder"]

  applications.fungus.controllers.LocationsDeleteController:
    class: ../../controllers/Locations/LocationsDeleteController
    arguments: ["@fungus.locations.LocationCleaner"]