imports:
  - { resource: ./application.yaml }

services:
  ##  Predictions
  fungus.predictions.WeatherStationRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/WeatherStations/InMemoryAEMETWeatherStationRepository
    arguments: []

  fungus.predictions.WeatherConditionRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/WeatherConditions/InMemoryWeatherConditionRepository
    arguments: []

  ##  Harvests
  fungus.harvests.HarvestRepository:
    class: ../../../../../src/Fungus/Harvests/Infrastructure/FileHarvestRepository
    arguments: []

  ##  Mushrooms
  fungus.mushrooms.MushroomRepository:
    class: ../../../../../src/Fungus/Mushrooms/Infrastructure/FileMushroomRepository
    arguments: []

  ##  Locations
  fungus.locations.LocationRepository:
    class: ../../../../../src/Fungus/Locations/Infrastructure/FileLocationRepository
    arguments: []

  fungus.locations.WeatherStationRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/WeatherStations/InMemoryAEMETWeatherStationRepository
    arguments: []
