imports:
  - { resource: ./application.yaml }

services:
  ##  Predictions
  fungus.predictions.WeatherStationRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/WeatherStations/InMemoryAEMETWeatherStationRepository
    arguments: []

  fungus.predictions.ConditionRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/InMemoryConditionRepository
    arguments: []

  ##  Harvests
  fungus.harvests.HarvestRepository:
    class: ../../../../../src/Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  ##  Mushrooms
  fungus.mushrooms.MushroomRepository:
    class: ../../../../../src/Fungus/Mushrooms/Infrastructure/InMemoryMushroomRepository
    arguments: []

  ##  Locations
  fungus.locations.LocationRepository:
    class: ../../../../../src/Fungus/Locations/Infrastructure/InMemoryLocationRepository
    arguments: []

  fungus.locations.WeatherStationRepository:
    class: ../../../../../src/Fungus/Predictions/Infrastructure/WeatherStations/InMemoryAEMETWeatherStationRepository
    arguments: [ ]
