
services:
  #  Health Checks
  applications.fungus.controllers.StatusGetController:
    class: ../../controllers/HealthChecks/StatusGetController
    arguments: []

  #  Harvests
  fungus.harvests.InMemoryHarvestRepository:
    class: ../../../../../Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  fungus.harvests.HarvestCreator:
    class: ../../../../../Fungus/Harvests/Application/create/HarvestCreator
    arguments: ["@fungus.harvests.InMemoryHarvestRepository", "@fungus.mushrooms.InMemoryMushroomRepository", "@fungus.locations.InMemoryLocationRepository"]

  applications.fungus.controllers.HarvestPutController:
    class: ../../controllers/Harvests/HarvestPutController
    arguments: ["@fungus.harvests.HarvestCreator"]

  #  Mushrooms
  fungus.mushrooms.InMemoryMushroomRepository:
    class: ../../../../../Fungus/Mushrooms/Infrastructure/InMemoryMushroomRepository
    arguments: []

  fungus.mushrooms.MushroomCreator:
    class: ../../../../../Fungus/Mushrooms/Application/create/MushroomCreator
    arguments: ["@fungus.mushrooms.InMemoryMushroomRepository"]

  applications.fungus.controllers.MushroomPutController:
    class: ../../controllers/Mushrooms/MushroomPutController
    arguments: ["@fungus.mushrooms.MushroomCreator"]

  #  Locations
  fungus.locations.InMemoryLocationRepository:
    class: ../../../../../Fungus/Locations/Infrastructure/InMemoryLocationRepository
    arguments: []

  fungus.locations.LocationCreator:
    class: ../../../../../Fungus/Locations/Application/create/LocationCreator
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  fungus.locations.LocationFinder:
    class: ../../../../../Fungus/Locations/Application/find/LocationFinder
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  fungus.locations.LocationCleaner:
    class: ../../../../../Fungus/Locations/Application/clean/LocationCleaner
    arguments: ["@fungus.locations.InMemoryLocationRepository"]

  applications.fungus.controllers.LocationPutController:
    class: ../../controllers/Locations/LocationPutController
    arguments: ["@fungus.locations.LocationCreator"]

  applications.fungus.controllers.LocationsGetController:
    class: ../../controllers/Locations/LocationsGetController
    arguments: ["@fungus.locations.LocationFinder"]

  applications.fungus.controllers.LocationsDeleteController:
    class: ../../controllers/Locations/LocationsDeleteController
    arguments: ["@fungus.locations.LocationCleaner"]