
services:
  fungus.harvests.InMemoryHarvestRepository:
    class: ../../../../../src/Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  fungus.harvests.HarvestRegistration:
    class: ../../../../../src/Fungus/Harvests/Application/register/HarvestRegistration
    arguments: ["@fungus.harvests.InMemoryHarvestRepository"]

  applications.fungus.controllers.HarvestPutController:
    class: ../../controllers/Harvests/HarvestPutController
    arguments: ["@fungus.harvests.HarvestRegistration"]

  applications.fungus.controllers.StatusGetController:
    class: ../../controllers/HealthChecks/StatusGetController
    arguments: []