
services:
  #  Health Checks
  applications.fungus.controllers.StatusGetController:
    class: ../../controllers/HealthChecks/StatusGetController
    arguments: []

  #  Harvests
  fungus.harvests.InMemoryHarvestRepository:
    class: ../../../../../src/Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  fungus.harvests.HarvestRegistration:
    class: ../../../../../src/Fungus/Harvests/Application/register/HarvestRegistration
    arguments: ["@fungus.harvests.InMemoryHarvestRepository"]

  applications.fungus.controllers.HarvestPutController:
    class: ../../controllers/Harvests/HarvestPutController
    arguments: ["@fungus.harvests.HarvestRegistration"]

  #  Mushrooms
  fungus.harvests.InMemoryMushroomRepository:
    class: ../../../../../src/Fungus/Mushrooms/Infrastructure/InMemoryMushroomRepository
    arguments: []

  fungus.mushrooms.MushroomCreator:
    class: ../../../../../src/Fungus/Mushrooms/Application/create/MushroomCreator
    arguments: ["@fungus.harvests.InMemoryMushroomRepository"]

  applications.fungus.controllers.MushroomPutController:
    class: ../../controllers/Mushrooms/MushroomPutController
    arguments: ["@fungus.mushrooms.MushroomCreator"]