
services:
  #  Health Checks
  applications.fungus.controllers.StatusGetController:
    class: ../../controllers/HealthChecks/StatusGetController
    arguments: []

  #  Harvests
  fungus.harvests.InMemoryHarvestRepository:
    class: ../../../../../src/Fungus/Harvests/Infrastructure/InMemoryHarvestRepository
    arguments: []

  fungus.harvests.HarvestCreator:
    class: ../../../../../src/Fungus/Harvests/Application/create/HarvestCreator
    arguments: ["@fungus.harvests.InMemoryHarvestRepository", "@fungus.mushrooms.InMemoryMushroomRepository"]

  applications.fungus.controllers.HarvestPutController:
    class: ../../controllers/Harvests/HarvestPutController
    arguments: ["@fungus.harvests.HarvestCreator"]

  #  Mushrooms
  fungus.mushrooms.InMemoryMushroomRepository:
    class: ../../../../../src/Fungus/Mushrooms/Infrastructure/InMemoryMushroomRepository
    arguments: []

  fungus.mushrooms.MushroomCreator:
    class: ../../../../../src/Fungus/Mushrooms/Application/create/MushroomCreator
    arguments: ["@fungus.mushrooms.InMemoryMushroomRepository"]

  applications.fungus.controllers.MushroomPutController:
    class: ../../controllers/Mushrooms/MushroomPutController
    arguments: ["@fungus.mushrooms.MushroomCreator"]